# Generated by Django 5.2.5 on 2025-09-04 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_bill_product_order_producttype_order_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='bill',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.RemoveField(
            model_name='producttype',
            name='order',
        ),
        migrations.RemoveField(
            model_name='producttype',
            name='product',
        ),
        migrations.DeleteModel(
            name='Bill',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Producttype',
        ),
    ]
