# Generated by Django 5.2.5 on 2025-09-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-first_name'], 'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.AddField(
            model_name='customer',
            name='slug',
            field=models.SlugField(blank=True, default=''),
        ),
    ]
